# Generated by Django 3.0.11 on 2020-11-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='ects',
            field=models.IntegerField(default=0, verbose_name='ECTS Punkte'),
        ),
        migrations.AddField(
            model_name='module',
            name='host',
            field=models.CharField(default='none', max_length=255, verbose_name='Anbieter des Moduls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='quota_cs',
            field=models.IntegerField(default=0, verbose_name='Anteil Informatik'),
        ),
        migrations.AddField(
            model_name='module',
            name='quota_economics',
            field=models.IntegerField(default=0, verbose_name='Anteil Wirtschaftswissenschaft'),
        ),
        migrations.AddField(
            model_name='module',
            name='quota_is',
            field=models.IntegerField(default=0, verbose_name='Anteil Wirtschaftsinformatik'),
        ),
        migrations.AddField(
            model_name='module',
            name='quota_key_competence',
            field=models.IntegerField(default=0, verbose_name='Anteil Schlüsselkompetenz'),
        ),
        migrations.AddField(
            model_name='module',
            name='term',
            field=models.CharField(choices=[('SS', 'Ss'), ('WS', 'Ws')], default='SS', max_length=2),
        ),
    ]
