# Generated by Django 3.0.11 on 2020-11-29 15:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terms', '0002_auto_20201125_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='term',
            field=models.CharField(choices=[('SS', 'Ss'), ('WS', 'Ws'), ('SS/WS', 'Ss/Ws')], default='SS', max_length=5),
        ),
        migrations.CreateModel(
            name='SemesterModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('term', models.DateField(choices=[(datetime.date(2020, 10, 1), 'Wintersemester 2020/21'), (datetime.date(2021, 4, 1), 'Sommersemester 2021'), (datetime.date(2021, 10, 1), 'Wintersemester 2021/22'), (datetime.date(2022, 4, 1), 'Sommersemester 2022'), (datetime.date(2022, 10, 1), 'Wintersemester 2022/23'), (datetime.date(2023, 4, 1), 'Sommersemester 2023')])),
                ('points_sl', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(18)], verbose_name='Punkte Studienleistung')),
                ('points_exam', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(18)], verbose_name='Punkte Klausur')),
                ('grade', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Note')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terms.Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
