# Generated by Django 3.0.11 on 2020-12-03 18:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_auto_20201129_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermodule',
            name='grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='semestermodule',
            name='points_exam',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(90)], verbose_name='Punkte Klausur'),
        ),
        migrations.AlterField(
            model_name='semestermodule',
            name='points_sl',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(18)], verbose_name='Punkte Studienleistung'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('start_date', models.DateTimeField(verbose_name='Start des Ereignisses')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Ende des Ereignisses')),
                ('event_type', models.CharField(choices=[('SC', 'Skriptabarbeitung'), ('SL', 'Studienleistung'), ('EA', 'Klausur Block A'), ('EB', 'Klausur Block B'), ('EC', 'Klausur Block C'), ('AL', 'Abstimmungstermin')], default='SC', max_length=2)),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('done', models.BooleanField(default=False, verbose_name='Erledigt?')),
                ('semestermodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terms.SemesterModule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
