# Generated by Django 3.0.11 on 2020-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0004_auto_20201203_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am'),
        ),
    ]
