# Generated by Django 3.0.11 on 2020-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0005_event_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ende des Ereignisses'),
        ),
    ]
