# Generated by Django 3.0.11 on 2020-12-13 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terms', '0006_auto_20201205_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermodule',
            name='done',
            field=models.BooleanField(default=False, null=True, verbose_name='Erledigt?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='semestermodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='terms.SemesterModule'),
        ),
        migrations.AlterField(
            model_name='semestermodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_modules', to='terms.Module'),
        ),
        migrations.AlterField(
            model_name='semestermodule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
