# Generated by Django 3.0.11 on 2020-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0007_auto_20201213_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermodule',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Erledigt?'),
        ),
    ]
