# Generated by Django 3.0.11 on 2020-12-16 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0008_auto_20201213_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='semestermodule',
            name='term',
            field=models.DateField(choices=[(datetime.date(2017, 10, 1), 'Wintersemester 2017/18'), (datetime.date(2018, 4, 1), 'Sommersemester 2018'), (datetime.date(2018, 10, 1), 'Wintersemester 2018/19'), (datetime.date(2019, 4, 1), 'Sommersemester 2019'), (datetime.date(2019, 10, 1), 'Wintersemester 2019/20'), (datetime.date(2020, 4, 1), 'Sommersemester 2020'), (datetime.date(2020, 10, 1), 'Wintersemester 2020/21'), (datetime.date(2021, 4, 1), 'Sommersemester 2021'), (datetime.date(2021, 10, 1), 'Wintersemester 2021/22'), (datetime.date(2022, 4, 1), 'Sommersemester 2022'), (datetime.date(2022, 10, 1), 'Wintersemester 2022/23'), (datetime.date(2023, 4, 1), 'Sommersemester 2023')]),
        ),
    ]
