# Generated by Django 3.0.11 on 2020-12-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0009_auto_20201216_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestermodule',
            options={'ordering': ['term']},
        ),
    ]
