# Generated by Django 3.0.11 on 2020-12-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0010_auto_20201217_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SC', 'Skriptbearbeitung'), ('SL', 'Studienleistung'), ('EA', 'Klausur Block A'), ('EB', 'Klausur Block B'), ('EC', 'Klausur Block C'), ('AL', 'Abstimmungstermin')], default='SC', max_length=2),
        ),
    ]
