# Generated by Django 3.0.11 on 2020-12-29 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0011_auto_20201219_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_modules', to='terms.Module', verbose_name='Modulbezeichnung'),
        ),
        migrations.AlterField(
            model_name='semestermodule',
            name='term',
            field=models.DateField(choices=[(datetime.date(2017, 10, 1), 'Wintersemester 2017/18'), (datetime.date(2018, 4, 1), 'Sommersemester 2018'), (datetime.date(2018, 10, 1), 'Wintersemester 2018/19'), (datetime.date(2019, 4, 1), 'Sommersemester 2019'), (datetime.date(2019, 10, 1), 'Wintersemester 2019/20'), (datetime.date(2020, 4, 1), 'Sommersemester 2020'), (datetime.date(2020, 10, 1), 'Wintersemester 2020/21'), (datetime.date(2021, 4, 1), 'Sommersemester 2021'), (datetime.date(2021, 10, 1), 'Wintersemester 2021/22'), (datetime.date(2022, 4, 1), 'Sommersemester 2022'), (datetime.date(2022, 10, 1), 'Wintersemester 2022/23'), (datetime.date(2023, 4, 1), 'Sommersemester 2023')], verbose_name='Semester'),
        ),
    ]
