# Generated by Django 3.0.11 on 2021-01-13 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0013_auto_20210113_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermodule',
            name='term',
            field=models.DateField(choices=[(datetime.date(2018, 10, 1), 'Wintersemester 2018/19'), (datetime.date(2019, 4, 1), 'Sommersemester 2019'), (datetime.date(2019, 10, 1), 'Wintersemester 2019/20'), (datetime.date(2020, 4, 1), 'Sommersemester 2020'), (datetime.date(2020, 10, 1), 'Wintersemester 2020/21'), (datetime.date(2021, 4, 1), 'Sommersemester 2021'), (datetime.date(2021, 10, 1), 'Wintersemester 2021/22')], verbose_name='Semester'),
        ),
    ]
