# Generated by Django 3.0.11 on 2021-01-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0014_auto_20210113_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
    ]
