# Generated by Django 3.0.11 on 2021-01-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0015_auto_20210116_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SC', 'Skriptbearbeitung'), ('SL', 'Studienleistung'), ('EA', 'Klausur Block A'), ('EB', 'Klausur Block B'), ('EC', 'Klausur Block C'), ('TP', 'Hausarbeit'), ('AL', 'Abstimmungstermin')], default='SC', max_length=2, verbose_name='Art des Ereignisses'),
        ),
    ]
